language: android

android:
  components:
    - build-tools-23.0.2
    - extra-android-m2repository
    - android-23
    - sys-img-armeabi-v7a-android-23

jdk:
  - oraclejdk8

script:
  - ./gradlew test
  - ./gradlew assemble


cache:
  directories:
    - $HOME/.gradle
